const state={fav:new Set(JSON.parse(localStorage.getItem('iseFav')||'[]')),cmp:JSON.parse(localStorage.getItem('iseCmp')||'[]'),quick:''};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const meta=p=>Object.assign({qsRank:null,qsDisplay:'Not verified',qsYear:2026,qsUrl:'#',courseUrl:'#',uniUrl:'#'},window.META[p.id]||{});
function save(){localStorage.setItem('iseFav',JSON.stringify([...state.fav]));localStorage.setItem('iseCmp',JSON.stringify(state.cmp))}
function fitClass(x){return x==='Return-safe'?'good':x==='Check exact exams'?'warn':'bad'}
function courseLinks(p){const m=meta(p);return `<a href="${esc(m.courseUrl)}" target="_blank" rel="noopener">Course page ↗</a><a href="${esc(m.uniUrl)}" target="_blank" rel="noopener">University ↗</a>`}
function card(p,compare=false){const m=meta(p);return `<article class="card"><h3>${esc(p.name)}</h3><div class="sub">${esc(p.location)} · ${esc(p.level)}</div><div class="badges"><span class="b ${fitClass(p.returnSafety)}">${esc(p.returnSafety)}</span><span class="b qsbadge">QS ${m.qsYear}: ${esc(m.qsDisplay)}</span><span class="b">${esc(p.climate||'Climate n/a')}</span><span class="b">${esc(p.region)}</span></div><div class="rows"><div><strong>Semester</strong><span>${esc(p.semester)}</span></div><div><strong>Weather</strong><span>${esc(p.temperature)}</span></div><div><strong>Travel</strong><span>${esc(p.travelText)}</span></div><div><strong>Verdict</strong><span>${esc(p.planning)}</span></div></div><div class="metrics"><div class="metric"><b>${p.overall}</b>Overall</div><div class="metric"><b>${p.calendar}</b>Calendar</div><div class="metric"><b>${p.ice}</b>ICE</div><div class="metric"><b>${p.travel}</b>Travel</div></div><div class="actions"><button class="primary" onclick="openModal(${p.id})">Details</button>${courseLinks(p)}${compare?'':`<button onclick="toggleCompare(${p.id})">${state.cmp.includes(p.id)?'Remove':'Compare'}</button><button class="fav ${state.fav.has(p.id)?'on':''}" onclick="toggleFav(${p.id})">${state.fav.has(p.id)?'★':'☆'}</button>`}</div></article>`}
function filtered(){let a=U.filter(p=>(!q.value||[p.name,p.location,p.country,p.region,p.level,p.planning,meta(p).qsDisplay].join(' ').toLowerCase().includes(q.value.toLowerCase()))&&(!region.value||p.region===region.value)&&(!fit.value||p.returnSafety===fit.value)&&(!climate.value||p.climate===climate.value));if(state.quick==='fav')a=a.filter(p=>state.fav.has(p.id));if(state.quick==='travel')a=a.filter(p=>p.travel>=8.8);return a}
function render(){let a=filtered();a.sort((a,b)=>sort.value==='name'?a.name.localeCompare(b.name):sort.value==='qs'?(meta(a).qsRank??99999)-(meta(b).qsRank??99999):(b[sort.value]||0)-(a[sort.value]||0));count.textContent=`${a.length} universities shown`;grid.innerHTML=a.length?a.map(p=>card(p)).join(''):'<div class="empty">No matching universities.</div>';renderCompare();renderRankings()}
function renderCompare(){let a=state.cmp.map(id=>U.find(p=>p.id===id)).filter(Boolean);compareGrid.innerHTML=a.length?a.map(p=>card(p,true)).join(''):'<div class="empty">No universities selected. Add up to three from Explore.</div>'}
function renderRankings(){const groups=[...new Set(U.map(x=>x.region))].sort();rankingsList.innerHTML=groups.map(regionName=>{const rows=U.filter(p=>p.region===regionName).sort((a,b)=>(meta(a).qsRank??99999)-(meta(b).qsRank??99999)).map(p=>{const m=meta(p);return `<tr><td class="ranknum">${esc(m.qsDisplay)}</td><td><b>${esc(p.name)}</b><div class="sub">${esc(p.location)}</div></td><td>${esc(p.returnSafety)}</td><td><a href="${esc(m.courseUrl)}" target="_blank" rel="noopener">Open course page ↗</a></td><td><a href="${esc(m.qsUrl)}" target="_blank" rel="noopener">QS profile ↗</a></td></tr>`}).join('');return `<section class="rank-region"><h3>${esc(regionName)}</h3><div class="table-wrap"><table class="rank-table"><thead><tr><th>QS 2026</th><th>University</th><th>Return fit</th><th>Courses</th><th>QS source</th></tr></thead><tbody>${rows}</tbody></table></div></section>`}).join('')}
function toggleFav(id){state.fav.has(id)?state.fav.delete(id):state.fav.add(id);save();render()}
function toggleCompare(id){let i=state.cmp.indexOf(id);if(i>=0)state.cmp.splice(i,1);else if(state.cmp.length<3)state.cmp.push(id);else alert('You can compare up to 3 universities.');save();render()}
function openModal(id){let p=U.find(x=>x.id===id),m=meta(p);mName.textContent=p.name;mSub.textContent=`${p.location} · ${p.level}`;mBody.innerHTML=`<div class="badges"><span class="b ${fitClass(p.returnSafety)}">${esc(p.returnSafety)}</span><span class="b">${esc(p.status)}</span><span class="b qsbadge">QS ${m.qsYear}: ${esc(m.qsDisplay)}</span><span class="b">${esc(p.climate)}</span></div><div class="scoregrid"><div class="scorebox"><b>${p.overall}</b>Overall</div><div class="scorebox"><b>${p.eligibility}</b>Eligibility</div><div class="scorebox"><b>${p.calendar}</b>Calendar</div><div class="scorebox"><b>${p.ice}</b>ICE</div></div><div class="detail-grid"><div class="detail"><h4>QS ranking</h4><p><b>QS World University Rankings ${m.qsYear}:</b> ${esc(m.qsDisplay)}</p><p>Specialist schools may not appear in the overall world ranking even when they are strong in a specific subject.</p></div><div class="detail"><h4>Semester and return</h4><p><b>Pattern:</b> ${esc(p.semester)}</p><p><b>Return assessment:</b> ${esc(p.returnSafety)}</p><p>${esc(p.planning)}</p></div><div class="detail"><h4>Typical weather</h4><p>${esc(p.temperature)}</p><p>Climate category: <b>${esc(p.climate)}</b></p></div><div class="detail"><h4>Travel opportunities</h4><p>${esc(p.travelText)}</p><p>Travel score: <b>${p.travel}/10</b></p></div><div class="detail"><h4>Restrictions / caution</h4><p>${esc(p.restriction||'No specific restriction recorded in the source set; host rules still apply.')}</p>${p.quotaSlots?`<p>Historical quota: <b>${p.quotaSlots} semester slot(s)</b></p>`:''}</div></div><div class="link-row"><a class="primary-link" href="${esc(m.courseUrl)}" target="_blank" rel="noopener">Browse official courses ↗</a><a href="${esc(m.uniUrl)}" target="_blank" rel="noopener">University website ↗</a><a href="${esc(m.qsUrl)}" target="_blank" rel="noopener">Open QS profile ↗</a></div><h3>Evidence used</h3><div class="source"><b>Source bucket:</b> ${esc(p.sourceBucket)}<br>${esc(p.evidence)}${p.quotaRemark?`<br><b>Quota remark:</b> ${esc(p.quotaRemark)}`:''}</div>`;modal.classList.add('on')}
function closeModal(){modal.classList.remove('on')}
modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.pane').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById(b.dataset.pane).classList.add('on');if(b.dataset.pane==='compare')renderCompare();if(b.dataset.pane==='rankings')renderRankings()});
[q,region,fit,climate,sort].forEach(x=>x.oninput=render);document.querySelectorAll('.quick button').forEach(b=>b.onclick=()=>{let v=b.dataset.q;document.querySelectorAll('.quick button').forEach(x=>x.classList.remove('on'));if(v==='clear'){q.value=region.value=fit.value=climate.value='';state.quick=''}else if(v==='Europe')region.value='Europe';else if(v==='Return-safe')fit.value='Return-safe';else if(v==='Warm')climate.value='Warm';else{state.quick=state.quick===v?'':v;b.classList.toggle('on',!!state.quick)}render()});
[...new Set(U.map(x=>x.region))].sort().forEach(x=>region.add(new Option(x,x)));render();