window.RETURN_POLICY={safeCutoff:'2027-12-31',mediumCutoff:'2028-01-16',description:'Return-safe means completion by 31 Dec 2027. Medium risk means the final required activity is between 1 and 16 Jan 2028, or the exact January date is not yet confirmed. High risk means 17 Jan 2028 or later.'};
window.RETURN_RISK={
1:{label:'Return-safe',note:'Semester normally finishes in early December.'},
2:{label:'Return-safe',note:'Semester normally finishes in early December.'},
3:{label:'Return-safe',note:'Term normally finishes in mid-December.'},
4:{label:'Return-safe',note:'Fall term finishes in late November.'},
5:{label:'Return-safe',note:'Semester normally finishes in November.'},
6:{label:'Return-safe',note:'Semester normally finishes in November.'},
7:{label:'Return-safe',note:'Semester normally finishes in November.'},
8:{label:'Return-safe',note:'Semester normally finishes in November.'},
9:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
10:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
11:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
12:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
13:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
14:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
15:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
16:{label:'Return-safe',note:'Semester normally finishes in December.'},
17:{label:'Return-safe',note:'Autumn teaching and assessment are normally completed in December.'},
19:{label:'Return-safe',note:'Autumn semester normally finishes in December.'},
22:{label:'Return-safe',note:'Fall examinations normally finish in late December.'},
23:{label:'Return-safe',note:'Fall semester normally finishes in December.'},
24:{label:'Return-safe',note:'Fall term normally finishes in December.'},
25:{label:'Return-safe',note:'Fall examinations normally finish in late December.'},
26:{label:'Medium risk',note:'Some courses may assess in early January. Confirm the last mandatory exam is no later than 16 Jan.'},
27:{label:'Medium risk',note:'Calendar may extend into early January. Confirm the last required assessment is no later than 16 Jan.'},
31:{label:'Medium risk',note:'Some first-term assessments may run into early January. Confirm the exact end date.'},
32:{label:'Medium risk',note:'Teaching may end in December but assessment can extend into early January. Confirm by 16 Jan.'},
33:{label:'Medium risk',note:'First-semester exams can run in January. Treat as medium only if your final exam is by 16 Jan.'},
35:{label:'Medium risk',note:'January assessment is possible. Medium only when your final required activity is by 16 Jan.'},
36:{label:'Medium risk',note:'January assessment is possible. Medium only when your final required activity is by 16 Jan.'},
37:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
38:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
39:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
40:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
41:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
42:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
43:{label:'High risk',note:'Semester or examinations may continue beyond 16 Jan and into February.'},
44:{label:'High risk',note:'Winter assessment can continue beyond 16 Jan and into February.'},
45:{label:'High risk',note:'First-semester examinations commonly continue beyond 16 Jan and into February.'},
46:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
47:{label:'Medium risk',note:'January assessment is possible. Confirm the final date is no later than 16 Jan.'},
48:{label:'High risk',note:'Autumn term normally continues beyond 16 Jan.'},
49:{label:'High risk',note:'Winter assessment can continue beyond 16 Jan and into February.'},
50:{label:'High risk',note:'Autumn term and examination period may continue beyond 16 Jan.'},
51:{label:'High risk',note:'First-semester examinations may continue beyond 16 Jan and into February.'},
52:{label:'High risk',note:'First-semester examinations may continue beyond 16 Jan and into February.'},
53:{label:'High risk',note:'The first term runs to around 30 Jan, beyond the 16 Jan threshold.'},
54:{label:'High risk',note:'First-semester examinations run into late January, beyond the 16 Jan threshold.'},
55:{label:'High risk',note:'Official autumn semester ends 17 Jan 2028, one day beyond the medium-risk cutoff.'}
};
(window.U||[]).forEach(function(p){var r=window.RETURN_RISK[p.id];if(r){p.returnSafety=r.label;p.returnRiskNote=r.note;}});
